#include "driver/i2s.h"
//#include "driver/i2s_std.h"
#include "I2Sto.h"

#define bufferLen 512
#include <stdio.h>

#include <stdint.h>
#include <stdlib.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "driver/gpio.h"
#include "esp_check.h"



// 音频配置
#define SAMPLE_RATE     44100       // 采样率（44.1kHz）
#define SAMPLE_BITS     I2S_BITS_PER_SAMPLE_16BIT // 每样本 16 位
#define DMA_BUF_COUNT   4           // DMA 缓冲区数量
#define DMA_BUF_LEN     1024        // 每个缓冲区的大小

#define EXAMPLE_STD_BCLK_IO1        15      // I2S bit clock io number   I2S_BCLK
#define EXAMPLE_STD_WS_IO1          16      // I2S word select io number    I2S_LRC
#define EXAMPLE_STD_DOUT_IO1        7     // I2S data out io number    I2S_DOUT
#define EXAMPLE_STD_DIN_IO1         GPIO_NUM_NC    // I2S data in io number

#define EXAMPLE_BUFF_SIZE               2048



void Init_i2s_0(){
    i2s_config_t i2s_config = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX),
        .sample_rate = 16000,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,
        .communication_format = (i2s_comm_format_t)(I2S_COMM_FORMAT_STAND_I2S),
        .intr_alloc_flags = 0,
        .dma_buf_count = 8,
        .dma_buf_len = bufferLen,
        .use_apll = false          // 分配中断标志
    };
    i2s_driver_install(I2S_NUM_0, &i2s_config, 0, NULL);
    i2s_pin_config_t pin_config = {
        .bck_io_num = 5,            // BCLK引脚号
        .ws_io_num = 4,             // LRCK引脚号
        .data_out_num = -1, // DATA引脚号
        .data_in_num = 6,           // DATA_IN引脚号
    };
    i2s_set_pin(I2S_NUM_0, &pin_config);
    i2s_start(I2S_NUM_0);
    printf("I2S_0初始化完成\n");
}
 
void Init_i2s_1(){
// 配置 I2S
i2s_config_t i2s_config = {
    .mode = I2S_MODE_MASTER | I2S_MODE_TX,  // 主机模式，只发送数据
    .sample_rate = 8000,             // 采样率
    .bits_per_sample = SAMPLE_BITS,         // 每样本位数
    .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,  // 立体声
    .communication_format = I2S_COMM_FORMAT_I2S,  // 标准 I2S 格式
    .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,     // 中断优先级
    .dma_buf_count = DMA_BUF_COUNT, // DMA 缓冲区数量
    .dma_buf_len = DMA_BUF_LEN,     // 每个缓冲区的大小
    .use_apll = false,              // 不使用 APLL，APLL即Audio PLL，音频锁相环
    .tx_desc_auto_clear = true,  // 自动清空 TX 描述符
};

// 配置 I2S 引脚
i2s_pin_config_t pin_config = {
    .bck_io_num = 15,  // BCLK 引脚
    .ws_io_num = 16,     // LRC 引脚
    .data_out_num = 7,  // DIN 引脚
    .data_in_num = -1    // 不使用输入
};

// 安装和启动 I2S 驱动
i2s_driver_install(I2S_NUM_1, &i2s_config, 0, NULL);
i2s_set_pin(I2S_NUM_1, &pin_config);
i2s_zero_dma_buffer(I2S_NUM_1);
printf("I2S_1初始化完成\n");
};

//  void Init_i2s_new_0(void)
// {
//     /* Setp 1: Determine the I2S channel configuration and allocate both channels
//      * The default configuration can be generated by the helper macro,
//      * it only requires the I2S controller id and I2S role */
//     printf("I2S_NUM_AUTO = %d\n", I2S_NUM_0);
//     i2s_chan_config_t chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_0, I2S_ROLE_MASTER);
//     ESP_ERROR_CHECK(i2s_new_channel(&chan_cfg, NULL, &rx_chan));

//     /* 步骤 2: 设置标准模式的配置，并初始化接收和发送通道
//      * 插槽配置和时钟配置可以通过宏生成
//      * 这些两个辅助宏定义在 'i2s_std.h' 中，仅可用于标准模式。
//      * 它们可以帮助指定初始化或重新配置的插槽和时钟配置 */
//     i2s_std_config_t std_cfg = {
//         .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(16000),
//         .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT, I2S_SLOT_MODE_MONO),
//         .gpio_cfg =
//             {
//                 .mclk = I2S_GPIO_UNUSED, // some codecs may require mclk signal, this example doesn't need it
//                 .bclk = 5,
//                 .ws = 4,
//                 .dout = I2S_GPIO_UNUSED,
//                 .din = 6, // 在双工模式下，将输出和输入绑定到同一个 GPIO 可以实现环回
//                 internally
//                 .invert_flags =
//                     {
//                         .mclk_inv = false,
//                         .bclk_inv = false,
//                         .ws_inv = false,
//                     },
//             },
//     };
//     /* 初始化通道 */
//     ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &std_cfg));
//     /* 默认情况下在单声道模式下仅接收左声道，
//      * 在此处更新为右声道，以演示如何更改默认配置 */
//     std_cfg.slot_cfg.slot_mask = I2S_STD_SLOT_LEFT;
//     ESP_ERROR_CHECK(i2s_channel_init_std_mode(rx_chan, &std_cfg));
// }

//  void Init_i2s_new_1(void) {
//     printf("I2S_NUM_AUTO = %d\n", I2S_NUM_1);
//     i2s_chan_config_t tx_chan_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_1, I2S_ROLE_MASTER);
//     ESP_ERROR_CHECK(i2s_new_channel(&tx_chan_cfg, &tx_chan, NULL));


//     i2s_std_config_t tx_std_cfg = {
//             .clk_cfg  = I2S_STD_CLK_DEFAULT_CONFIG(44100),
//             .slot_cfg = I2S_STD_MSB_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_32BIT,
//                                                         I2S_SLOT_MODE_MONO),

//             .gpio_cfg = {
//                     .mclk = I2S_GPIO_UNUSED,    // some codecs may require mclk signal, this example doesn't need it
//                     .bclk = 15,
//                     .ws   = 16,
//                     .dout = 7,
//                     .din  = -1,
//                     .invert_flags = {
//                             .mclk_inv = false,
//                             .bclk_inv = false,
//                             .ws_inv   = false,
//                     },
//             },
//     };
//     ESP_ERROR_CHECK(i2s_channel_init_std_mode(tx_chan, &tx_std_cfg));
// }

